# Generated by Django 5.0 on 2025-05-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college_id',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
    ]
